name: cruizr
description: A cycling tracking app with Firebase authentication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # UI
  google_fonts: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.2
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  intl: ^0.19.0
  
  # Google Maps
  google_maps_flutter: ^2.6.1
  geolocator: ^10.0.0
  flutter_polyline_points: ^2.1.0
  http: ^1.2.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true