name: cruizr
description: A cycling tracking app with Firebase authentication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_functions: ^6.0.5
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # UI
  google_fonts: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.2
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  intl: ^0.19.0
  
  # Google Maps
  google_maps_flutter: ^2.10.0
  geolocator: ^10.0.0
  flutter_polyline_points: ^2.1.0
  http: ^1.2.0
  permission_handler: ^12.0.1
  pointer_interceptor: ^0.10.1
  url_launcher: ^6.3.2
  flutter_secure_storage: ^10.0.0
  uni_links: ^0.5.1
  cached_network_image: ^3.4.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  flutter_image_compress: ^2.4.0
  shared_preferences: ^2.2.2
  
  # Calendar
  table_calendar: ^3.1.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true